// The Settings tab's field schema — one entry per configurable setting, driving
// both the category sidebar counts and the field renderer picked in SettingsTab.
import { DEFAULT_PROVIDER_MODELS } from '@/constants/models';
import { DEFAULT_BACKEND_URL } from '@/hooks/useSettings';

export interface SettingField {
  id: string;
  category: string;
  label: string;
  description: string;
  type: 'string' | 'password' | 'list' | 'boolean' | 'select';
  defaultValue: any;
  options?: { label: string; value: string }[];
}

export const SETTING_FIELDS: SettingField[] = [
  {
    id: 'anthropic_api_key',
    category: 'Anthropic',
    label: 'Anthropic Api Key',
    description: 'Enter the API Key for your official Anthropic Claude account. By using this preference, the key is saved securely in your browser local storage.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'anthropic_models',
    category: 'Anthropic',
    label: 'Anthropic Models',
    description: 'List of official and custom Anthropic Claude models available for code modernization.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.anthropic,
  },
  {
    id: 'openai_api_key',
    category: 'OpenAI',
    label: 'OpenAI Api Key',
    description: 'Enter the API Key for your OpenAI GPT developer account. This key is used to execute chat completions and code writers.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'openai_models',
    category: 'OpenAI',
    label: 'OpenAI Models',
    description: 'List of official OpenAI GPT models available for modernization loops.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.openai,
  },
  {
    id: 'google_api_key',
    category: 'Google',
    label: 'Google Api Key',
    description: 'Enter the Google Gemini developer API Key. Make sure the Gemini API is enabled in your Google Cloud console.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'google_models',
    category: 'Google',
    label: 'Google Models',
    description: 'Google Gemini generative models registered for scanning and conversions.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.google,
  },
  {
    id: 'google_max_retries',
    category: 'Google',
    label: 'Max Retries On Errors',
    description: 'Maximum number of retries in case of request errors. If smaller than 1, then the retry logic is disabled.',
    type: 'string',
    defaultValue: '3',
  },
  {
    id: 'google_retry_delay_rate_limit',
    category: 'Google',
    label: 'Retry Delay On Rate Limit Error',
    description: 'Delay in seconds between retries in case of rate limit errors (429 Too Many Requests).',
    type: 'string',
    defaultValue: '60',
  },
  {
    id: 'google_retry_delay_other',
    category: 'Google',
    label: 'Retry Delay On Other Errors',
    description: 'Delay in seconds between retries in case of other errors (syntax, 500, timeouts). Set to -1 to disable retries in these cases.',
    type: 'string',
    defaultValue: '-1',
  },
  {
    id: 'grok_api_key',
    category: 'Grok',
    label: 'Grok (xAI) Api Key',
    description: 'Enter the API Key for your xAI Grok developer account.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'grok_models',
    category: 'Grok',
    label: 'Grok Models',
    description: 'List of Grok models available for code modernization.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.grok,
  },
  {
    id: 'groq_api_key',
    category: 'Groq',
    label: 'Groq Api Key',
    description: 'Enter the API Key for your official Groq developer account.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'groq_models',
    category: 'Groq',
    label: 'Groq Models',
    description: 'List of official Groq models available for code modernization.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.groq,
  },
  {
    id: 'openrouter_api_key',
    category: 'OpenRouter',
    label: 'OpenRouter Api Key',
    description: 'Enter the API Key for your OpenRouter developer account.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'openrouter_models',
    category: 'OpenRouter',
    label: 'OpenRouter Models',
    description: 'List of OpenRouter models available for code modernization.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.openrouter,
  },
  {
    id: 'mistral_api_key',
    category: 'Mistral',
    label: 'Mistral Api Key',
    description: 'Enter the API Key for your official Mistral AI (La Plateforme) account. Supports mistral-large, mistral-small, and codestral models.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'mistral_models',
    category: 'Mistral',
    label: 'Mistral Models',
    description: 'List of Mistral AI models available for code modernization. codestral-latest is recommended for code-heavy migrations.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.mistral,
  },
  {
    id: 'mistral_max_retries',
    category: 'Mistral',
    label: 'Max Retries On Errors',
    description: 'Maximum number of retries in case of request errors. If smaller than 1, then the retry logic is disabled.',
    type: 'string',
    defaultValue: '3',
  },
  {
    id: 'mistral_retry_delay_rate_limit',
    category: 'Mistral',
    label: 'Retry Delay On Rate Limit Error',
    description: 'Delay in seconds between retries in case of rate limit errors (429 Too Many Requests).',
    type: 'string',
    defaultValue: '60',
  },
  {
    id: 'mistral_retry_delay_other',
    category: 'Mistral',
    label: 'Retry Delay On Other Errors',
    description: 'Delay in seconds between retries in case of other errors (syntax, 500, timeouts). Set to -1 to disable retries in these cases.',
    type: 'string',
    defaultValue: '-1',
  },
  {
    id: 'huggingface_api_key',
    category: 'Hugging Face',
    label: 'Hugging Face Api Key',
    description: 'Enter the API Token for your Hugging Face account.',
    type: 'password',
    defaultValue: '',
  },
  {
    id: 'huggingface_models',
    category: 'Hugging Face',
    label: 'Hugging Face Models',
    description: 'List of Hugging Face models available for code modernization.',
    type: 'list',
    defaultValue: DEFAULT_PROVIDER_MODELS.huggingface,
  },
  {
    id: 'general_backend_url',
    category: 'General',
    label: 'Backend API Service URL',
    description: 'The target port and host address of the running Express code migration server engine.',
    type: 'string',
    defaultValue: DEFAULT_BACKEND_URL,
  },
  {
    id: 'general_local_output_path',
    category: 'General',
    label: 'Local Output Workspace Path',
    description: 'Specify an absolute local path on your computer where the modernized project files and reports should be written directly (e.g. E:\\Naveen\\modernized-app). If blank, they are saved inside the backend sessions folder.',
    type: 'string',
    defaultValue: '',
  },
  {
    id: 'general_desktop_notifications',
    category: 'General',
    label: 'Desktop Notifications for Checkpoints',
    description: 'Show a native OS notification when a migration reaches a checkpoint (Stage 1 complete, awaiting graph review, error) while this tab isn\'t focused. Requires browser permission.',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'general_github_client_id',
    category: 'General',
    label: 'GitHub OAuth App Client ID (Override)',
    description: '"Sign in with GitHub" (bottom-left) already works with no setup, using this platform\'s own default OAuth App. Only set this if you are self-hosting and want GitHub sign-in to use YOUR OWN OAuth App (Device Flow enabled) instead of the platform default. Leave blank otherwise.',
    type: 'string',
    defaultValue: '',
  },
  {
    id: 'general_theme',
    category: 'General',
    label: 'Color Theme',
    description: 'Select the color theme of the editor workspace interface.',
    type: 'select',
    defaultValue: 'dark',
    options: [
      { label: 'Dark (Visual Studio)', value: 'dark' },
      { label: 'Light (Visual Studio)', value: 'light' },
      { label: 'High Contrast', value: 'hc' },
    ],
  },
];
